# Funding options for Halt
# Uncomment and add your funding platforms

# github: [yourusername]
# patreon: yourusername
# open_collective: halt
# ko_fi: yourusername
# custom: ['https://yourwebsite.com/donate']
